hw(ya_liubnytskyi):dictionary
v-angolenko/python-course-2023 pull request #67
Opened 2023-11-25 14:14 UTC by FAZZlK

2023-12-21 10:36 UTC, v-angolenko requested changes

2023-12-21 10:36 UTC, v-angolenko commented on ya_liubnytskyi/dictionary/1_menu.py
> +print(f"Меню: \n {menu[0]} - {menu_prices['coffee']} грн \n {menu[1]} - {menu_prices['tea']} грн \n {menu[2]} - {menu_prices['water']} грн")
Это следует все таки вывести с помощью цикла

2023-12-21 10:36 UTC, v-angolenko commented on ya_liubnytskyi/dictionary/2_products.py
> +print(f"In storage {product_stock['apples']} {product_list[0]}, {product_stock['bananas']} {product_list[1]}")
Это тоже с помощью цикла

2023-12-25 10:17 UTC, ltlaitoff commented on ya_liubnytskyi/dictionary/1_menu.py
> +# 1. Створіть словник `menu_prices` з назвами страв та їхніми цінами.
@v-angolenko Доброго ранку! Наскільки я розумію, цей репозиторій для навчання студентів університету мові python.

Ви точно зі студентів робите інженерів, а не розробників, які можуть написати код по заданому алгоритму, да і тільки?

Давати повний алгоритм як зробити завдання - це крінж. Студент, який буде робити це завдання навіть не буде думати, що і як працює. Він не буде навчатись нормальному неймінгу та гарним практикам створення проєктів. Він буде просто робити все по алгоритму, який ви дали. А потім на реальному проекті буде сидіти та дуже довго тупити, бо готового алгоритму немає, а GPT не допомагає.

Це завдання людина може закинути в gpt та отримати точно такой код, як цей бо всі подібні коди будуть однаковими!

Ви не навчаєте людину думати головою та намагатись зрозуміти як буде краще щось написати. Ви просто даєте алгоритм. Це точно навчання?

2024-05-30 07:47 UTC, closed without merging